---
- name: Deploy E-commerce Application Containers
  hosts: web
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - { role: common, tags: ["common", "docker"] }
    - { role: repo_clone, tags: ["repo"] }
    - { role: database, tags: ["database"] }
    - { role: backend, tags: ["backend"] }
    - { role: frontend, tags: ["frontend"] }
