---
- name: Ensure app directory exists
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Clone the application repo
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_dir }}"
    version: "{{ app_branch }}"
    force: yes
  become_user: vagrant
  tags: ["repo"]
